name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  tf-destroy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CLIENT_NAME: jaiditya

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_KEY}}
          role-session-name: ci-run-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Write SSH Key from GitHub Secrets
        run: |
          echo "${{ secrets.EC2_TOKEN }}" > my_key.pem
          chmod 600 my_key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: flask-server-bucket-2
          AWS_BUCKET_KEY_NAME: state/terraform-${{env.CLIENT_NAME}}.tfstate
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve -var "image_tag=$IMAGE_TAG"
