name: Provision EC2 and Deploy Flask

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      DOCKER_HUB_REPO: vampconnoisseur/flask-server
      IMAGE_TAG: ${{ github.run_number }}
      INSTANCE_NAME: flask-server
      CLIENT_NAME: jaiditya
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_KEY}}
          role-session-name: ci-run-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./flask_backend
          file: ./flask_backend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }}

      - name: Write SSH Key from GitHub Secrets
        run: |
          echo "${{ secrets.EC2_TOKEN }}" > my_key.pem
          chmod 600 my_key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: flask-server-bucket-2
          AWS_BUCKET_KEY_NAME: state/terraform-${{env.CLIENT_NAME}}.tfstate
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var "image_tag=$IMAGE_TAG"

      - name: Get Public IP
        run: |
          echo "Public IP: $(terraform output -raw public_ip)"

      - name: Cleanup SSH Key
        if: always()
        run: rm -f my_key.pem
